### ISSUE TITLE
Server crashes on player trying to travel to the Nether

### ISSUE THREAD

**Issue by Not-February** [TheRandomLabs/Vertical-End-Portals#1]
https://gist.github.com/Febilian/472ac0567d92e4f9f7a2c9d1707d0070

Using default configs of the mod.

**Comment by TheRandomLabs** [comment]
This was fixed in 1.12.2-0.6.0.0.

**Comment by Not-February** [comment]
Oof, right when I was sure I had the latest version! Sorry to bother.
