### ISSUE TITLE
Wrong Portal Type Created

### ISSUE THREAD

**Issue by Mattabase** [TheRandomLabs/Vertical-End-Portals#11]
https://mattadatta.page.link/LAtm

**Comment by TheRandomLabs** [comment]
I can't reproduce this. Is it possible that the lateral portal was already there when you entered the vertical portal?

**Comment by Mattabase** [comment]
Completely new world, with a void nether. I was able to stop it from happening by changing the json to now allow horizontal portals, which lead to this happening again. 
https://mattadatta.page.link/K78v

**Comment by TheRandomLabs** [comment]
I've fixed the platform position, but I still can't get a lateral portal to generate.

**Comment by TheRandomLabs** [comment]
Reopen if this is still an issue.
