### ISSUE TITLE
Custom block for Portals reset on game relaunch

### ISSUE THREAD

**Issue by Compegen** [TheRandomLabs/Vertical-End-Portals#13]
I have set a custom block as the portal block in a pack I'm making. It works when set in game, but once the pack is relaunched, it clears the block field back to empty.

Using version: 1.6.5.0

**Comment by Compegen** [comment]
This is happening for any portal I try making. It is also a modded block I'm trying to make the portal out of

**Comment by TheRandomLabs** [comment]
Strange, I'll look at this soon.

**Comment by TheRandomLabs** [comment]
The portal types were being loaded too early in initialization. I'll release a fix now, sorry!

**Comment by kragnoth** [comment]
I'm getting this with immersive engineering reinforced coal coke brick blocks.  Is there a recommended behavior to make sure you're using a block that's already loaded?

**Comment by TheRandomLabs** [comment]
Whoops, I know why this is happening.
