### ISSUE TITLE
[Suggestion] Spawn first portal in dimension at X/Y/Z

### ISSUE THREAD

**Issue by CREEATION** [TheRandomLabs/Vertical-End-Portals#15]
Not sure if this is already possible, but I'm trying to create a creative flat dimension where the very first portal created should be at `0/10/0`, so players can easily `/tp` to `0 ~ 0` to get to the main portal.

**Comment by TheRandomLabs** [comment]
Good idea! I'll implement a way to specify destination coordinates in the next release.

**Comment by TheRandomLabs** [comment]
Sorry for the late reply, but this has been implemented and will be released once I add a few other features.
