### ISSUE TITLE
When using Random Portals with SpongeForge portals are not generated.

### ISSUE THREAD

**Issue by Renari** [TheRandomLabs/Vertical-End-Portals#17]
It seems spawn locations are often inside walls and return portals are not generated when used with Sponge Forge.

**Comment by TheRandomLabs** [comment]
Interesting. I'll look into this.

**Comment by TheRandomLabs** [comment]
This was fixed in 1.12.2-1.8.0.2, but I'm not sure if there are any side effects.

**Comment by TheRandomLabs** [comment]
Resolved.
