### ISSUE TITLE
Continous RightClickBlock Event triggering Nullpointer Exception

### ISSUE THREAD

**Issue by LarcekGiglamesh** [TheRandomLabs/Vertical-End-Portals#18]
• Modpack: Mystical Skies v1.5.1
• RandomPortals Version: randomportals-1.12.2-1.7.0.1
• Spongeforge Version: spongeforge-1.12.2-2768-7.1.5-RC3515
• Log File: https://pastebin.com/DFZEg2Lh
(not sure where it starts, or where it ends)

It indicates the Issue being here on line 50:
https://github.com/TheRandomLabs/RandomPortals/blob/1.12.2/src/main/java/com/therandomlabs/randomportals/handler/NetherPortalActivationHandler.java

I feel the Event is triggering continously even when nobody is around. I'm not sure if this is a side effect, but Events requiring Right Clicks (Eating Food, Opening Books) will only work when facing Blocks.

**Comment by TheRandomLabs** [comment]
Can you take RandomPortals out and see if the error still occurs? If so, can I have a full log?

**Comment by LarcekGiglamesh** [comment]
We Updated to latest Modpack Version but it still happens:
• Modpack: Mystical Skies v1.6.2
• RandomPortals Version: randomportals-1.12.2-1.7.0.1

I started the server, joined, unvanished, took a Lexica Botania and opened it a few times, then went to restart. 

[2019-04-16-6.log](https://github.com/TheRandomLabs/RandomPortals/files/3085901/2019-04-16-6.log)

**edit:**
The Issue is solved if RandomPortals is disabled and returns when enabled again.

**Comment by TheRandomLabs** [comment]
Thanks for the full log. This is fixed in the next release, although it is strange that RightClickBlock would be called like that.
