### ISSUE TITLE
Null Pointer Exeption

### ISSUE THREAD

**Issue by Draskh** [TheRandomLabs/Vertical-End-Portals#19]
I made red portal and tried travelling to the Nether.
[crash-2019-05-24_16.18.11-server.txt](https://github.com/TheRandomLabs/RandomPortals/files/3217285/crash-2019-05-24_16.18.11-server.txt)

**Comment by TheRandomLabs** [comment]
Strange, it looks like the correct teleporter isn't being used, meaning this is probably a compatibility issue. Can I have `debug.log`?

**Comment by TheRandomLabs** [comment]
Can you try again with 1.12.2-1.8.0.2?

**Comment by Draskh** [comment]
That was my fault. Due to an old config alternative teleporter was set to false.
