### ISSUE TITLE
Mod Conflict - Moving World

### ISSUE THREAD

**Issue by Aexoyir** [TheRandomLabs/Vertical-End-Portals#2]
Crash with Moving World 1.12.6-342full

When I remove Random Portals (also last three versions) but leave Random Patches and Random Integration the game launches fine. With this mod added Moving World throws this error:
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moving World (movingworld)
Caused by: java.lang.NullPointerException
	at com.elytradev.movingworld.common.config.priority.AssemblePriorityConfig.discoverPoweredBlocks(AssemblePriorityConfig.java:168)`

Not sure if this is more your issue or theirs...

Full log for ref:
[2018-12-13-5.log](https://github.com/TheRandomLabs/RandomPortals/files/2678387/2018-12-13-5.log)

Looking forward to using your mod,
Aexoyir

**Comment by TheRandomLabs** [comment]
MovingWorld is loading `Blocks.PORTAL` (the Nether portal block) and `Blocks.END_PORTAL` (the End portal block) before RandomPortals registers its own versions, then is using them after RandomPortals has registered its replacements. This could probably be fixed on their end by using `ObjectHolder`s, but I can just get my mod to load before theirs.

**Comment by TheRandomLabs** [comment]
This is fixed in 1.12.2-0.9.0.1. RandomPortals now manually replaces MovingWorld's references to the old portal blocks to its own ones.
