### ISSUE TITLE
[1.12.2] Netherportal block lost name 

### ISSUE THREAD

**Issue by Draskh** [TheRandomLabs/Vertical-End-Portals#20]
After I removed RandomPortals all portal blocks turned into tile.null.name. Although I created a new world this is still happening. Theses blocks are destroyable by hand even in survival mode.
![2019-05-27_12 25 15](https://user-images.githubusercontent.com/26455012/58414199-fff32100-807a-11e9-9846-31ea0cd803b7.png)

**Comment by TheRandomLabs** [comment]
Nether portal blocks don't have a name in vanilla Minecraft. If it really bugs you but you don't want to have RandomPortals installed, [RandomTweaks](https://minecraft.curseforge.com/projects/randomtweaks) also fixes this.

**Comment by Draskh** [comment]
Normally TOP displays Nether Portal and they should be breakable by hand in survival mode. This came up after I removed RandomPortals. I have RandomPatches installed. Can this mod cause it?

**Comment by TheRandomLabs** [comment]
Looks like you're right, sorry. RandomPatches shouldn't touch it.

**Comment by TheRandomLabs** [comment]
Do you have RandomTweaks installed?

**Comment by Draskh** [comment]
No. I just installed Random Patches for higher server time out due to the large size of my pack.

**Comment by TheRandomLabs** [comment]
Strange, looks like a mod is setting the Nether portal's localized name to `null`, but if you don't have RandomTweaks installed, I don't know which one it could be.
RandomPortals/RandomTweaks set the translation key at runtime, so any changes shouldn't persist after a restart.

**Comment by Draskh** [comment]
NetherEX? Only mod that does much to Nether I guess.
Maybe installing RandomTweaks might fix it?

**Comment by TheRandomLabs** [comment]
It would fix it, but you shouldn't have to. It's not NetherEx as far as I can tell. It could still be that I screwed something up.

**Comment by Draskh** [comment]
I found this in the log.https://pastebin.com/JnjHrvuM
There a still old IDs in the save although I have loaded the world before. Shouldn't they have been removed? Maybe it is  conflict with Just Enough IDs saving format I use?

**Comment by Draskh** [comment]
https://github.com/mekanism/Mekanism/issues/5590
