### ISSUE TITLE
When i open a world it crashes

### ISSUE THREAD

**Issue by glamorized** [TheRandomLabs/Vertical-End-Portals#26]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/22/19 9:17 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at com.therandomlabs.randomportals.world.RPOTeleporter.onWorldLoad(RPOTeleporter.java:870)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_RPOTeleporter_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:132)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 173165200 bytes (165 MB) / 570425344 bytes (544 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID            | Version         | Source                            | Signature                                |
	|:------- |:------------- |:--------------- |:--------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft     | 1.12.2          | minecraft.jar                     | None                                     |
	| UCHIJAA | mcp           | 9.42            | minecraft.jar                     | None                                     |
	| UCHIJAA | FML           | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge         | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | randompatches | 1.12.2-1.19.1.1 | randompatches-1.12.2-1.19.1.1.jar | None                                     |
	| UCHIJAA | randomportals | 1.12.2-1.8.1.1  | randomportals-1.12.2-1.8.1.1.jar  | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |

	Loaded coremods (and transformers): 
RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TheRandomLabs** [comment]
You need to use a newer version of Forge.
