### ISSUE TITLE
Vertical Purple Portal Texture Broken

### ISSUE THREAD

**Issue by sixarms** [TheRandomLabs/Vertical-End-Portals#27]
Lateral vanilla portal texture shows off fine, but normal vertical portals have texture issues.

I noticed that with the mod it definitely lets you select the portal block item, likely so you can edit them with dyes.  But for some reason it's not referencing any texture.

Included a picture of the issue on imgur:

[https://i.imgur.com/ArXlcFz.png](https://i.imgur.com/ArXlcFz.png)

**Comment by TheRandomLabs** [comment]
This is a minor incompatibility with Inspirations. I'll make it so that Inspirations' custom portal color option is automatically disabled.
