### ISSUE TITLE
Weird crashes

### ISSUE THREAD

**Issue by Shattered2909** [TheRandomLabs/Vertical-End-Portals#30]
i was trying to use the mod in my pack (darkest journey 2) yesterday and was just messing around trying to make a portal between the overworld and betweenlands work, first i kept getting this crash:
https://pastebin.com/txPudBm6
apparently it was because i disabled some end portal parts, enabling them again stopped the crashes from happening, then i think i made the portal kinda load? then got this crash when trying to activate the portal:
https://pastebin.com/YWsa9AA9

also my config:
https://pastebin.com/dXWhjfCz

**Comment by TheRandomLabs** [comment]
This is a compatibility issue with Topography. Luckily, this should be an easy fix. Can you see if the latest version I uploaded works?

**Comment by Shattered2909** [comment]
Gonna try

**Comment by Shattered2909** [comment]
Sorry for not reacting in a while, had to do other things in the pack recently...

**Comment by TheRandomLabs** [comment]
Nah, it's all good.

**Comment by Shattered2909** [comment]
Okay, I've been messing around a little bit, most things work now BUT: the end gateway/portal issue is still around.

Also for some reason I cannot use custom items from Contenttweaker as Portal Activator, assume those are created later after RP is loaded. Don't know if this can be fixed at all...

EDIT: This also means that custom blocks from Contenttweaker cannot be used as Portal Frames which reaaaaaaally sucks.

**Comment by TheRandomLabs** [comment]
Alright, thanks for reporting. I'll look at it soon.

**Comment by TheRandomLabs** [comment]
This might be fixed now. Sorry for the late response! Let me know if it's not fixed.
