### ISSUE TITLE
[Question] Trouble Creating Portals That Work From Any World

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [TheRandomLabs/Vertical-End-Portals#31]
I'm having some issues creating portals. I took a look at the example portals page and have been basing mine off those. However, I keep running into issues and would greatly appreciate some help. 

I have a lot of worlds. I'd like players in X world to be able to use Y portal to get to Z world. Then they can use that same portal to get back to X world.

For example, I tried creating a portal that goes **to the overworld (id=0)**. And I'd like players to be able to create this portal in any other dimension/world to get between the two worlds. Is this possible? I tried doing this and going to the overworld works but then going back to the original world doesn't; they just to the default world stated in group_data.json

The files below are for creating a portal that goes to the overworld (id=0) and the portal should be possible to create in any other world. And in case the mod cannot find that world it goes to the world with the id=3 (AKA the "BoP Advanced World").
Folder: to_vanillaplus_main_overworld
3.json: https://pastebin.com/DqtQdcZq
group_data.json: https://pastebin.com/3sqtWbwy

Feedback would be greatly appreciated. Thank you!

**Comment by TheRandomLabs** [comment]
So I wasn't going to work on the 1.12.2 version of this mod anymore, but it seemed simple enough to implement. Set `destination.ensureReturnToSameDimension` to `true`. :P

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> So I wasn't going to work on the 1.12.2 version of this mod anymore, but it seemed simple enough to implement. Set `destination.ensureReturnToSameDimension` to `true`. :P

Thank you so much! <3

**Comment by PiggiesGoSqueal** [comment]
@TheRandomLabs Well, I updated the jar & tried it. Unfortunately it didn't seem to work.

Main world = dim 0
BoP Advanced world = dim 3
Resource world = dim 4

I was in dim 4 and created a portal that leads to dim 0. I went in it and successfully went to dim 0. But then I tried to go back to dim 4 and it brought me to dim 3 instead.

Should I be naming the 3.json file something different for it to work to return to the same dimension?

My Files were:
3.json: https://pastebin.com/LTjJPQx5
group_data.json: https://pastebin.com/3sqtWbwy

In 3.json I had set:
"ensureReturnToSameDimension": to true. 

-------------------------
I then tried renaming 3.json to 0.json (the destination world)
And in group_data.json I changed "defaultDimensionID": 3, to 0 (the destination world).
Because I wasn't sure what else to do. I started off in dim 4, used the portal to go to dim 0, then tried to go back to dim 4 via the portal but it wouldn't let me and stayed in dim 0 as expected.

Help would be appreciated. Thank you! :)

**Comment by PiggiesGoSqueal** [comment]
Interesting. I just noticed in the reference portal example on Github there was already a ensureReturnToSameDimension option?

https://github.com/TheRandomLabs/RandomPortals/blob/misc/Custom%20Portal%20Examples/reference_portal/0.json

Line 131. Although it didn't seem to work either I believe.
