### ISSUE TITLE
Activation dimension whitelist?

### ISSUE THREAD

**Issue by HeatherComputer** [TheRandomLabs/Vertical-End-Portals#36]
Is it possible to change the activation dimension blacklist in `group_data.json` to a whitelist?

**Comment by HeatherComputer** [comment]
Okay, from further work it seems the only dimension that actually works is dim0, no matter the config?

**Comment by TheRandomLabs** [comment]
I don't believe so, and I'm not willing to work on 1.12.2 code anymore.

**Comment by TheRandomLabs** [comment]
The best solution is to enable `blacklistAllUndefinedDimensions` in `group_data.json`.

**Comment by HeatherComputer** [comment]
What about the latter issue though, where the portal doesn't activate outside of dim0 even with the blacklist empty?

**Comment by TheRandomLabs** [comment]
Have you defined portals for each dimension?

**Comment by HeatherComputer** [comment]
I have `0..json` in one of the groups, defining a glass portal leading to dimension 8. There are no blacklisted dimensions for activation. It can only be activated in the overworld. Any idea why?

**Comment by TheRandomLabs** [comment]
You'll have to show me your `0.json` and `group_data.json`.

**Comment by HeatherComputer** [comment]
[0.json](https://github.com/TheRandomLabs/RandomPortals/files/6064791/0.json.txt)
[group_data.json](https://github.com/TheRandomLabs/RandomPortals/files/6064792/group_data.json.txt)

Github doesn't directly support json files, so I changed the extension. Same contents though.

**Comment by TheRandomLabs** [comment]
Your first file is a copy of the second.

**Comment by HeatherComputer** [comment]
[0.json](https://github.com/TheRandomLabs/RandomPortals/files/6068120/0.json.txt)

I'm not sure why, I've just checked contents locally and they show what they should. Is this better?

**Comment by TheRandomLabs** [comment]
Does the vanilla Nether portal activate in other dimensions?

**Comment by HeatherComputer** [comment]
> Does the vanilla Nether portal activate in other dimensions?

No, it doesn't.
