### ISSUE TITLE
Crash when traveling through portal

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TheRandomLabs/Vertical-End-Portals#5]
Crash log: https://pastebin.com/cFBWhhJT

I added a new portal type with this path: `config/randomportals/vanilla_nether_portal/75.json`

If can be found here: https://pastebin.com/JUbw5i0Z

It crashes when I travel though the portal, and continues to crash when I load back into the world

**Comment by TheRandomLabs** [comment]
The crash will be fixed in the next version - it should have defaulted to the overworld when it couldn't find dimension 75. However, that doesn't explain why dimension 75 couldn't be found.

**Comment by TheDeviantCrafter** [comment]
Dimension is a custom Mystcraft age. I can teleport to it using `/tpx`, but maybe Mystcraft does something strange.

**Comment by TheRandomLabs** [comment]
Can you see if 1.12.2-1.6.2.1 works? I've improved the dimension ID validation.

**Comment by TheRandomLabs** [comment]
Assuming this is fixed.
