### ISSUE TITLE
[Help] Some questions I don't see answered on the wiki

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TheRandomLabs/Vertical-End-Portals#6]
1. How am I supposed to configure the JSON file structure? Do I need to create a new folder in the `config/randomportals` directory for each portal type, or add them to `config/randomportals/custom_nether_portal`?

2. What's the difference between `defaultDimensionID` in the `group_data.json` file and "dimensionID" in the `0.json` file? The wiki doesn't try to explain the second one. 

3. I set up something a portal that sort of worked. I created a new filed in `config/randomportals/custom_nether_portal` named `75.json` and set the dimension ID to 75. It only worked in dimension 75, but I couldn't create a portal in the overworld. What did I do wrong?

**Comment by TheRandomLabs** [comment]
1. I've updated the documentation to specify the file structure.

2. The function of `defaultDimensionID` is explained in `reference_portal/group_data.json`, but in short, it's the dimension ID that RandomPortals falls back to when it can't determine which dimension a portal should teleport to.

3. It's strange that it worked at all. That directory shouldn't be recognized by RandomPortals.

**EDIT**: Unless you actually put it in `config/randomportals/portal_types/custom_nether_portal`.

**Comment by TheDeviantCrafter** [comment]
That's the path I put it in. My bad.
