### ISSUE TITLE
Blocks in the portal "Frame" cloned in to portal formed in the nether. 

### ISSUE THREAD

**Issue by Mattabase** [TheRandomLabs/Vertical-End-Portals#8]
The portal that is created in the nether clones any block in the portal "frame" shape form the portal in the overworld. 

I my case, I had a chest and basalt in the corners and it created them in the resulting portal in the nether. 

The portal was also shifted to the right of the platform on either side of the portal so the player easily falls off when entering.

**Comment by TheRandomLabs** [comment]
I'll add an option to stop the corners from being cloned.
